Models/payment/payment.cs
namespace Peajes.Models.payment
{
    public class payment
    {
        public int id { get; set; }

        public string matricula { get; set; }

        public bool pagado { get; set; }

        public int IdVehiculo { get; set; }

        public string CreateAt { get; set; }
    }
}

Controllers/paymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Peajes.Data;
using Peajes.Models.payment;
using Peajes.Models.entity;

namespace Peajes.Controllers
{
    public class paymentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public paymentsController(ApplicationDbContext context)
        {
            _context = context;
        }
        private bool PaymentExists(int id)
        {
            return _context.payment.Any(e => e.id == id);
        }


        // GET: payments
        public async Task<IActionResult> Index()
        {
            var payments = await _context.payment.ToListAsync();
            var vehiculos = await _context.Vehiculo.ToListAsync();
            var Motos = await _context.Moto.ToListAsync();
            var Camions = await _context.Camion.ToListAsync();
            var Colectivos = await _context.Colectivo.ToListAsync();

            var viewModel = new PaymentsViewModel
            {
                Payments = payments,
                Vehiculos = vehiculos,
                Motos = Motos,
                Camions = Camions,
                Colectivos = Colectivos
            };

            return View(viewModel);
        }

        // GET: payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.payment
                .FirstOrDefaultAsync(m => m.id == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: payments/Create
        public IActionResult Create(string matricula = null, int IdVehiculo = 0 )
        {
            var payment = new payment
            {
                matricula = matricula,
                IdVehiculo = IdVehiculo
            };
            return View(payment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,matricula,pagado,IdVehiculo")] payment payment)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(payment);
                    await _context.SaveChangesAsync();

                    // Llama al método Delete de VehiculoController para eliminar el vehículo
                    var vehiculoController = new VehiculoController(_context);
                    var deleteResult = await vehiculoController.Delete(payment.IdVehiculo, true);


                    if (deleteResult is OkResult) // Revisa si la eliminación fue exitosa
                    {
                        return RedirectToAction("Index", "Payments");
                    }
                    else
                    {
                        // Maneja el caso donde la eliminación no fue exitosa
                        return NotFound(); // Puedes ajustar esto según el manejo que desees
                    }
                }
                catch (Exception e)
                {
                    // Handle the exception here
                    // Log the error or perform any necessary actions
                    // You can also return a specific error view or message
                    return View("Error", e);
                }
            }
            return View(payment);
        }



        // GET: payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.payment.FindAsync(id);
            if (payment == null)
            {
                return NotFound();
            }
            return View(payment);
        }

        // POST: payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,matricula,pagado")] payment payment)
        {
            if (id != payment.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!paymentExists(payment.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(payment);
        }

        // GET: payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.payment
                .FirstOrDefaultAsync(m => m.id == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // POST: payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payment = await _context.payment.FindAsync(id);
            _context.payment.Remove(payment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool paymentExists(int id)
        {
            return _context.payment.Any(e => e.id == id);
        }
    }

    public class PaymentsViewModel
    {
        public List<payment> Payments { get; set; }
        public List<Vehiculo> Vehiculos { get; set; }
        public List<Moto> Motos { get; set; }
        public List <Camion> Camions { get; set; }
        public List<Colectivo> Colectivos { get; set;}
    }
}

Views/payments/Create.cshtml
@model Peajes.Models.payment.payment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>payment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="matricula" class="control-label"></label>
                <input asp-for="matricula" class="form-control" value="@Model.matricula" />
                <span asp-validation-for="matricula" class="text-danger"></span>

                <label asp-for="IdVehiculo" class="control-label"></label>
                <input asp-for="IdVehiculo" class="form-control" value="@Model.IdVehiculo" />
                <span asp-validation-for="IdVehiculo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="pagado" /> @Html.DisplayNameFor(model => model.pagado)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/payments/Delete.cshtml
@model Peajes.Models.payment.payment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>payment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pagado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pagado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/payments/Details.cshtml
@model Peajes.Models.payment.payment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>payment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pagado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pagado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/payments/Edit.cshtml
@model Peajes.Models.payment.payment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>payment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="matricula" class="control-label"></label>
                <input asp-for="matricula" class="form-control" />
                <span asp-validation-for="matricula" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="pagado" /> @Html.DisplayNameFor(model => model.pagado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/payments/Index.cshtml
@model Peajes.Controllers.PaymentsViewModel

@{
    ViewData["Title"] = "Payments Index";
}

<h1>Payments</h1>



<h3>Vehiculos Pendientes a pagar</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Vehiculos.First().id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehiculos.First().matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehiculos.First().modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehiculos.First().marca)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Vehiculos)  
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.matricula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.marca)
                </td>
                <td>
                    @Html.ActionLink("Pagar", "Create", "payments", new { matricula = item.matricula, IdVehiculo = item.id }, null)

                    @Html.ActionLink("Details", "Details", "Vehiculo", new { id = item.id }, null) |
                    @Html.ActionLink("Delete", "Delete", "Vehiculo", new { id = item.id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>
<h3>Motos Pendientes a pagar</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Motos.First().id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Motos.First().matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Motos.First().modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Motos.First().marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Motos.First().cilindraje)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Motos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.matricula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cilindraje)
                </td>
                <td>
                    @Html.ActionLink("Pagar", "Create", "payments", new { matricula = item.matricula }, null) |
                    @Html.ActionLink("Details", "Details", "Moto", new { id = item.id }, null) |
                    @Html.ActionLink("Delete", "Delete", "Vehiculo", new { id = item.id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>
<h3>Camion Pendientes a pagar</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Camions.First().id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Camions.First().matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Camions.First().modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Camions.First().marca)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Camions)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.matricula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.marca)
                </td>
                <td>
                    @Html.ActionLink("Pagar", "Create", "payments", new { matricula = item.matricula }, null) |
                    @Html.ActionLink("Details", "Details", "Moto", new { id = item.id }, null) |
                    @Html.ActionLink("Delete", "Delete", "Vehiculo", new { id = item.id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>
<h3>Colectivos Pendientes a pagar</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Colectivos.First().id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Colectivos.First().matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Colectivos.First().modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Colectivos.First().marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Colectivos.First().pisos)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Colectivos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.matricula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.pisos)
                </td>
                <td>
                    @Html.ActionLink("Pagar", "Create", "payments", new { matricula = item.matricula }, null) |
                    @Html.ActionLink("Details", "Details", "Moto", new { id = item.id }, null) |
                    @Html.ActionLink("Delete", "Delete", "Vehiculo", new { id = item.id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>